qdevice_cfg: &qdevice_cfg
  num_qubits: 3
  num_comm_qubits: 1
  T1: 1.e+10
  T2: 1.e+9
  init_time: 1.e+4
  single_qubit_gate_time: 1.e+3
  two_qubit_gate_time: 1.e+5
  measurement_time: 1.e+4
  single_qubit_gate_depolar_prob: 0
  two_qubit_gate_depolar_prob: 0.01

stacks:
  - name: sender
    qdevice_typ: nv
    qdevice_cfg: 
      <<: *qdevice_cfg
    classical_cfg:
      host_qnos_latency: 1e5
  - name: receiver
    qdevice_typ: nv
    qdevice_cfg: 
      <<: *qdevice_cfg
    classical_cfg:
      host_qnos_latency: 1e5
  
link_cfg: &link_cfg
  length_A: 0.01
  length_B: 0.01
  full_cycle: 1e6
  cycle_time: 1e3
  alpha: 0.9

links:
  - stack1: sender
    stack2: receiver
    typ: nv
    cfg:
      <<: *link_cfg